[package]
name = "furiosa-device"
version = "0.1.0"
authors = ["FuriosaAI SW Team <pkg@furiosa.ai>"]
edition = "2021"
description = "APIs that offer FuriosaAI NPU devices' information and allow to control the devices"
license = "Apache-2.0"
homepage = "https://furiosa.ai"
repository = "https://github.com/furiosa-ai/device-api"

[features]
blocking = [] # Enable blocking APIs

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "list_npu"
path = "bin/list_npu.rs"

[[bin]]
name = "list_npu_blocking"
path = "bin/list_npu_blocking.rs"
required-features = ["blocking"]

[dependencies]
array_tool = "1"
cli-table = "0.4"
lazy_static = "1.4"
enum-display-derive = "0.1"
itertools = "0.10"
regex = "1.5"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3.1", features = ["env-filter", "json"] }
tokio = { version = "1.17.0", features = ["fs", "rt-multi-thread", "macros"] }
