[package]
name = "furiosa-device-api"
version = "0.1.0"
authors = ["FuriosaAI SW Team <pkg@furiosa.ai>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
regex = "1.5"
enum-display-derive = "0.1"
tokio = { version = "1.13.1", features = ["fs", "full"] }
itertools = "0.10"
array_tool = "1"